bind = "unix:app.sock"
workers = 4
pidfile = 'pidfile'
errorlog = 'errorlog'
loglevel = 'info'
accesslog = 'accesslog'
access_log_format = '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"'
certfile = '/etc/letsencrypt/live/wanderpi.duckdns.org/fullchain.pem'
keyfile = '/etc/letsencrypt/live/wanderpi.duckdns.org/privkey.pem'